NAME = test_cpp_lib
BUILDPATH = build
# BUILD_CONFIG = execute
# BUILD_CONFIG = multibuild

BUILD_CONFIG = library
# LIBRARY_TYPE = static
# LIBRARY_TYPE = shared
LIBRARY_TYPE = both

LANG = cpp
# LANG = c

INCLUDE_PATHS = include
SOURCE_PATH = src

include ../make_rules/makerules.mk
